VioletGames/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using VioletGames.Data.Filters;
using VioletGames.Data.Repositorio;
using VioletGames.Models;
using VioletGames.Util.Validator;

namespace VioletGames.Controllers
{
    [PageUserLogin]
    public class ClienteController : Controller
    {
        //Extrai variavel ClienteRepositorio
        private readonly IClienteRepositorio _clienteRepositorio;

        public ClienteController(IClienteRepositorio clienteRepositorio)
        {
            //injeta para dentro de ClienteController
            _clienteRepositorio = clienteRepositorio;
        }

        public IActionResult Index()
        {
            //lista a busca feita no banco
            ViewData["Title"] = "Clientes";
            List<ClienteModel> clientes = _clienteRepositorio.SearchAll();
            
            return View(clientes);
        }
        public IActionResult Create()
        {
            ViewData["Title"] = "Clientes";
            return View();
        }

        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Clientes";
            ClienteModel cliente = _clienteRepositorio.ListForIDClient(id);
            return View(cliente);
        }

        public IActionResult DeleteConfirm(int id)
        {
            ViewData["Title"] = "Clientes";
            ClienteModel cliente = _clienteRepositorio.ListForIDClient(id);

            return View(cliente);
        }

        public IActionResult Delete(int id)
        {
            try{
                bool deleted = _clienteRepositorio.Delete(id);

                if (deleted)
                {
                    TempData["MessagemSucess"] = "Cliente deletado com sucesso!";
                }
                else
                {
                    TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente.";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult PayPlan(int id)
        {
            ClienteModel cliente = _clienteRepositorio.ListForIDClient(id);

            return RedirectToAction("PayPlan", "Caixa", cliente);
        }


        //Métodos Post
        [HttpPost]
        public IActionResult Create(ClienteModel cliente)
        {
            try{
                if (ModelState.IsValid)
                {
                    if (!Validator.IsCPF(cliente.CPF))
                    {
                        TempData["MessagemError"] = "CPF informado Inválido!";
                        return View(cliente);
                    }
                    if (!Validator.IsPhone(cliente.Phone))
                    {
                        TempData["MessagemError"] = "Telefone informado Inválido!";
                        return View(cliente);
                    }

                    if(!Validator.IsDateValid(cliente.DateBirthday))
                    {
                        TempData["MessagemError"] = "Data informada Inválida!";
                        return View(cliente);
                    }

                    if (cliente.Plano != Data.Enums.Plan.Free) cliente.payment = Data.Enums.StatusPayment.Pendente;
                    if (cliente.Plano == Data.Enums.Plan.Free) cliente.payment = Data.Enums.StatusPayment.Pago;

                    _clienteRepositorio.Create(cliente);
                    TempData["MessagemSucess"] = "Cliente cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(cliente);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível efetuar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
            
        }

        [HttpPost]
        public IActionResult Edit(ClienteModel cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!Validator.IsCPF(cliente.CPF))
                    {
                        TempData["MessagemError"] = "CPF informado Inválido!";
                        return View(cliente);
                    }
                    if (!Validator.IsPhone(cliente.Phone))
                    {
                        TempData["MessagemError"] = "Telefone informado Inválido!";
                        return View(cliente);
                    }
                    _clienteRepositorio.Update(cliente);
                    TempData["MessagemSucess"] = "Cadastro editado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(cliente);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível editar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

VioletGames/Controllers/ConsoleController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using VioletGames.Models;
using VioletGames.Data.Repositorio;
using VioletGames.Data.Filters;

namespace VioletGames.Controllers
{
    [PageUserLogin]
    public class ConsoleController : Controller
    {
        private readonly IConsoleRepositorio _consoleRepositorio;

        public ConsoleController(IConsoleRepositorio consoleRepositorio)
        {
            _consoleRepositorio = consoleRepositorio;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Consoles";
            List<ConsoleModel> consoles = _consoleRepositorio.SearchAll();

            return View(consoles);
        }

        public IActionResult Create()
        {
            ViewData["Title"] = "Consoles";
            return View();
        }

        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Consoles";
            ConsoleModel console = _consoleRepositorio.ListForID(id);
            
            return View(console);
        }

        public IActionResult DeleteConfirm(int id)
        {
            ViewData["Title"] = "Consoles";
            ConsoleModel console = _consoleRepositorio.ListForID(id);

            return View(console);
        }

        public IActionResult Delete(int id)
        {
            try{
                bool deleted = _consoleRepositorio.Delete(id);
                
                if (deleted)
                {
                    TempData["MessagemSucess"] = "Console deletado com sucesso!";
                }
                else
                {
                    TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente.";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
            
        }

        //Métodos Post
        [HttpPost]
        public IActionResult Create(ConsoleModel console)
        {
            try{
                if (ModelState.IsValid) 
                {
                    _consoleRepositorio.Create(console);
                    TempData["MessagemSucess"] = "Console cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(console);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível efetuar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(ConsoleModel console)
        {
            try{
                if (ModelState.IsValid)
                {
                    _consoleRepositorio.Update(console);
                    TempData["MessagemSucess"] = "Cadastro editado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(console);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível editar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

    }
}

VioletGames/Controllers/JogoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using VioletGames.Models;
using VioletGames.Data.Repositorio;
using VioletGames.Data.Filters;

namespace VioletGames.Controllers
{
    [PageUserLogin]
    public class JogoController : Controller
    {
        private readonly IJogoRepositorio _jogoRepositorio;

        public JogoController(IJogoRepositorio jogoRepositorio)
        {
            _jogoRepositorio = jogoRepositorio;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Jogos";
            List<JogoModel> jogos = _jogoRepositorio.SearchAll();

            return View(jogos);
        }

        public IActionResult Create()
        {
            ViewData["Title"] = "Jogos";
            return View();
        }

        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Jogos";
            JogoModel jogo = _jogoRepositorio.ListForID(id);
            
            return View(jogo);
        }

        public IActionResult DeleteConfirm(int id)
        {
            ViewData["Title"] = "Jogos";
            JogoModel jogo = _jogoRepositorio.ListForID(id);

            return View(jogo);
        }

        public IActionResult Delete(int id)
        {
            try{
                bool deleted = _jogoRepositorio.Delete(id);
                
                if (deleted)
                {
                    TempData["MessagemSucess"] = "Jogo deletado com sucesso!";
                }
                else
                {
                    TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente.";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
            
        }

        //Métodos Post
        [HttpPost]
        public IActionResult Create(JogoModel jogo)
        {
            try{
                if (ModelState.IsValid) 
                {
                    _jogoRepositorio.Create(jogo);
                    TempData["MessagemSucess"] = "Jogo cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(jogo);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível efetuar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(JogoModel jogo)
        {
            try{
                if (ModelState.IsValid)
                {
                    _jogoRepositorio.Update(jogo);
                    TempData["MessagemSucess"] = "Cadastro editado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(jogo);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível editar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

    }
}

VioletGames/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using VioletGames.Data.Filters;
using VioletGames.Data.Repositorio;
using VioletGames.Models;

namespace VioletGames.Controllers
{
    [PageUserLogin]
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepositorio _produtoRepositorio;

        public ProdutoController(IProdutoRepositorio produtoRepositorio)
        {
            _produtoRepositorio = produtoRepositorio;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Produtos";
            List<ProdutoModel> produtos = _produtoRepositorio.SearchAll();

            return View(produtos);
        }

        public IActionResult Create()
        {
            ViewData["Title"] = "Produtos";
            return View();
        }

        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Produtos";
            ProdutoModel produto = _produtoRepositorio.ListForID(id);
            
            return View(produto);
        }

        public IActionResult DeleteConfirm(int id)
        {
            ViewData["Title"] = "Produtos";
            ProdutoModel produto = _produtoRepositorio.ListForID(id);

            return View(produto);
        }

        public IActionResult Delete(int id)
        {
            try{
                bool deleted = _produtoRepositorio.Delete(id);

                if (deleted)
                {
                    TempData["MessagemSucess"] = "Produto deletado com sucesso!";
                }
                else
                {
                    TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente.";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
            

        //Métodos Post
        [HttpPost]
        public IActionResult Create(ProdutoModel produto)
        {
            try{
                if(ModelState.IsValid)
                {
                    _produtoRepositorio.Create(produto);
                    TempData["MessagemSucess"] = "Produto cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(produto);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível efetuar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(ProdutoModel produto)
        {
            try{
                if (ModelState.IsValid)
                {
                    _produtoRepositorio.Update(produto);
                    TempData["MessagemSucess"] = "Cadastro editado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(produto);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível editar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

VioletGames/Views/Shared/Components/Menu/Default.cshtml
@model UsuarioModel

<header class="bar">
    <!--usar bar pro login-->
    <nav class="navbar navbar-dark" id="Top">
        <div class="container">
            <button class="navbar-toggler" onclick="openMenu()" id="btnMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="invisible">//</a><a id="tittleMenu" class="navbar-brand mr-auto">@ViewData["Title"]</a>
            <a class="navbar-brand" style="color:white;">Olá, @Model.Login </a>
            <div class="dropdown">
                <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown">
                    <img src="~/lib/users/user1.png" width="50" height="50" class="user" />
                </button>
                <div class="dropdown-menu btn-primary">
                    <a role="button" class="dropdown-item btn-primary" asp-controller="ResetPasswdUser" asp-action="Index">Alterar Senha</a>
                    <a role="button" class="dropdown-item btn-primary" href="https://github.com/melissa-mfs/Violet_Games/blob/Master/TCC-mei/TCC_Violet_Games.pdf" >Ajuda</a>
                </div>
            </div>
        </div>
    </nav>
</header>
<!--id determina o objeto-->
<nav class="nav-menu" id="Menu">
    <div style="margin-left:16.5%" onclick="closeMenu()">
        <img src="~/lib/img/icon.png" width="150" height="150">
        <a class="nav-link" style="font-family: 'Agency FB'; color: white; background-color: transparent !important; font-size: 30px; ">Violet_Games</a>
    </div>
    <ul class="nav flex-column">
        <li><a role="button" class="nav-link" asp-controller="Dashboard" asp-action="Index"><img src="~/lib/bottons/monitor.png" width="40" height="40"> Dashboard</a></li>
        <li><a role="button" class="nav-link" asp-controller="Caixa" asp-action="Index"><img src="~/lib/bottons/car.png" width="40" height="40"> Caixa</a></li>
        <li><a role="button" class="nav-link" asp-controller="Produto" asp-action="Index"><img src="~/lib/bottons/stockg.png" width="40" height="40"> Produtos</a></li>
        <li><a role="button" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="font-family: Consolas; color: white;">
            <img src="~/lib/bottons/location.png" width="40" height="40"> Locação</a>
            <ul class="dropdown-menu">
                <li><a role="button" class="nav-link" asp-controller="Agendamento" asp-action="Index"><img src="~/lib/bottons/SchedulerWhite.png" width="40" height="40"> Agendamentos</a></li>
                <li><a role="button" class="nav-link" asp-controller="Console" asp-action="Index"><img src="~/lib/bottons/console.png" width="40" height="40"> Consoles</a></li>
                <li><a role="button" class="nav-link" asp-controller="Jogo" asp-action="Index"><img src="~/lib/bottons/joystick.png" width="40" height="40"> Jogos</a></li>
            </ul></li>
        <li><a role="button" class="nav-link" asp-controller="Cliente" asp-action="Index"><img src="~/lib/bottons/vip.png" width="40" height="40"> Clientes</a></li>

        @if (Model.Perfil == VioletGames.Data.Enums.PerfilEnum.Admin)
        {
            <li><a role="button" class="nav-link" asp-controller="Funcionario" asp-action="Index"><img src="~/lib/bottons/user.png" width="40" height="40"> Funcionários</a></li>
            <li><a role="button" class="nav-link" asp-controller="Usuario" asp-action="Index"><img src="~/lib/bottons/userMenu.png" width="40" height="40"> Usuários</a></li>
        }

        <li><a role="button" class="nav-link" asp-controller="Login" asp-action="Exit"><img src="~/lib/bottons/exit.png" width="35" height="35"> Sair</a></li>
    </ul>
    <div class="container footer" style="font-size: 16px; color: white; background-color: transparent !important; text-transform: none;">
        <span>&copy; Develop by </span><a href="https://github.com/melissa-mfs" style="font-size: 16px; color: white; background-color: transparent !important;">Melissa-MFS</a>
    </div>
</nav>