VioletGames/Controllers/AgendamentoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using VioletGames.Models;
using VioletGames.Data.Repositorio;
using VioletGames.Data.Filters;
using VioletGames.Data.Enums;
using VioletGames.Data.Helper;
using VioletGames.Util.Validator;

namespace VioletGames.Controllers
{
    [PageUserLogin]
    public class AgendamentoController : Controller
    {
        private readonly IAgendamentoRepositorio _agendamentoRepositorio;
        private readonly IJogoRepositorio _jogoRepositorio;
        private readonly IConsoleRepositorio _consoleRepositorio;
        private readonly ISessionUser _session;
        private readonly IClienteRepositorio _clienteRepositorio;

        public AgendamentoController(IAgendamentoRepositorio agendamentoRepositorio, IJogoRepositorio jogoRepositorio, 
                                        IConsoleRepositorio consoleRepositorio ,ISessionUser sessionUser,
                                        IClienteRepositorio clienteRepositorio)
        {
            _agendamentoRepositorio = agendamentoRepositorio;
            _jogoRepositorio = jogoRepositorio;
            _consoleRepositorio = consoleRepositorio;
            _clienteRepositorio = clienteRepositorio;
            _session = sessionUser;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Agendamentos";
            List<AgendamentoModel> agendamentos = _agendamentoRepositorio.SearchAll();

            return View(agendamentos);
        }

        public IActionResult CreateConsole(int id)
        {
            ViewData["Title"] = "Agendamentos";
            AgendamentoModel agendamento = new AgendamentoModel();
            try
            {
                UsuarioModel usuarioLogin = _session.SeachSessionUser();
                ConsoleModel console = _consoleRepositorio.ListForID(id);

                agendamento.LoginUser = usuarioLogin.Login;
                agendamento.DateSchedule = DateTime.Today;
                agendamento.DateEnter = DateTime.Now;
                agendamento.Payment = StatusPayment.Pendente;

                if (console != null)
                {
                    agendamento.NameGameOrConsole = console.Name;
                    agendamento.Category = CategoryProduct.Console;
                    agendamento.TotalValue = console.PriceHour;
                }
                return View(agendamento);
            }
            catch (System.Exception erro) {
                TempData["MessagemError"] = $"Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult CreateGame(int id)
        {
            ViewData["Title"] = "Agendamentos";
            AgendamentoModel agendamento = new AgendamentoModel();
            try
            {
                UsuarioModel usuarioLogin = _session.SeachSessionUser();
                JogoModel jogo = _jogoRepositorio.ListForID(id);

                agendamento.LoginUser = usuarioLogin.Login;
                agendamento.DateSchedule = DateTime.Today;
                agendamento.DateEnter = DateTime.Now;
                agendamento.Payment = StatusPayment.Pendente;

                if (jogo != null)
                {
                    agendamento.Category = CategoryProduct.Game;
                    agendamento.NameGameOrConsole = jogo.Name;
                    agendamento.TotalValue = jogo.PriceHour;
                }

                return View(agendamento);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Agendamentos";
            AgendamentoModel agendamento = _agendamentoRepositorio.ListForID(id);
            
            return View(agendamento);
        }

        public IActionResult DeleteConfirm(int id)
        {
            ViewData["Title"] = "Agendamentos";
            AgendamentoModel agendamento = _agendamentoRepositorio.ListForID(id);

            return View(agendamento);
        }

        public IActionResult Delete(int id)
        {
            try{
                bool deleted = _agendamentoRepositorio.Delete(id);
                
                if (deleted)
                {
                    TempData["MessagemSucess"] = "Agendamento deletado com sucesso!";
                }
                else
                {
                    TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente.";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
            
        }

        public IActionResult PayScheduling(int id)
        {
            AgendamentoModel agendamento = _agendamentoRepositorio.ListForID(id);

            return RedirectToAction("PayScheduling", "Caixa", agendamento);
        }

        //Métodos Post
        [HttpPost]
        public IActionResult CreateGame(AgendamentoModel agendamento)
        {
            try{
                if (ModelState.IsValid) 
                {
                    if (!Validator.IsCPF(agendamento.CPFClient))
                    {
                        TempData["MessagemError"] = "CPF inválido!";
                        return View(agendamento);
                    }

                    if (!_clienteRepositorio.isClient(agendamento.CPFClient))
                    {
                        TempData["MessagemError"] = "Cliente não encontrado!";
                        return View(agendamento);
                    }

                    ClienteModel cliente = _clienteRepositorio.ListForCPF(agendamento.CPFClient);
                    agendamento.NameClient = cliente.Name;

                    _agendamentoRepositorio.Create(agendamento);
                    TempData["MessagemSucess"] = "Agendamento cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(agendamento);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível efetuar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult CreateConsole(AgendamentoModel agendamento)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Console.WriteLine(agendamento.DateClose.Value.Day + " e "+ agendamento.DateEnter.Day);
                    Console.WriteLine(agendamento.DateClose.Value.Month + " e "+ agendamento.DateEnter.Month);

                    if(agendamento.DateClose.Value.Day != agendamento.DateEnter.Day ||
                    agendamento.DateClose.Value.Month != agendamento.DateEnter.Month)
                    {
                        TempData["MessagemError"] = "Data de agendamento de console inválida!";
                        return View(agendamento);
                    }
                    if (!Validator.IsCPF(agendamento.CPFClient))
                    {
                        TempData["MessagemError"] = "CPF inválido!";
                        return View(agendamento);
                    }

                    if (!_clienteRepositorio.isClient(agendamento.CPFClient))
                    {
                        //Criar msgbox: deseja cadastrar o cliente novo?
                        TempData["MessagemError"] = "Cliente não encontrado!";
                        return View(agendamento);
                    }
                    ClienteModel cliente = _clienteRepositorio.ListForCPF(agendamento.CPFClient);
                    agendamento.NameClient = cliente.Name;

                    _agendamentoRepositorio.Create(agendamento);
                    TempData["MessagemSucess"] = "Agendamento cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(agendamento);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível efetuar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(AgendamentoModel agendamento)
        {
            try{
                if (ModelState.IsValid)
                {
                    if (!Validator.IsCPF(agendamento.CPFClient))
                    {
                        TempData["MessagemError"] = "CPF inválido!";
                        return View(agendamento);
                    }

                    if (!_clienteRepositorio.isClient(agendamento.CPFClient))
                    {
                        TempData["MessagemError"] = "Cliente não encontrado!";
                        return View(agendamento);
                    }
                    ClienteModel cliente = _clienteRepositorio.ListForCPF(agendamento.CPFClient);
                    agendamento.NameClient = cliente.Name;
                    
                    if(agendamento.Category == CategoryProduct.Console)
                    {
                        ConsoleModel console = _consoleRepositorio.ListForName(agendamento.NameGameOrConsole);
                        agendamento.TotalValue = console.PriceHour;
                    }
                    if (agendamento.Category == CategoryProduct.Game)
                    {

VioletGames/Controllers/JogoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using VioletGames.Models;
using VioletGames.Data.Repositorio;
using VioletGames.Data.Filters;

namespace VioletGames.Controllers
{
    [PageUserLogin]
    public class JogoController : Controller
    {
        private readonly IJogoRepositorio _jogoRepositorio;

        public JogoController(IJogoRepositorio jogoRepositorio)
        {
            _jogoRepositorio = jogoRepositorio;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Jogos";
            List<JogoModel> jogos = _jogoRepositorio.SearchAll();

            return View(jogos);
        }

        public IActionResult Create()
        {
            ViewData["Title"] = "Jogos";
            return View();
        }

        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Jogos";
            JogoModel jogo = _jogoRepositorio.ListForID(id);
            
            return View(jogo);
        }

        public IActionResult DeleteConfirm(int id)
        {
            ViewData["Title"] = "Jogos";
            JogoModel jogo = _jogoRepositorio.ListForID(id);

            return View(jogo);
        }

        public IActionResult Delete(int id)
        {
            try{
                bool deleted = _jogoRepositorio.Delete(id);
                
                if (deleted)
                {
                    TempData["MessagemSucess"] = "Jogo deletado com sucesso!";
                }
                else
                {
                    TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente.";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
            
        }

        //Métodos Post
        [HttpPost]
        public IActionResult Create(JogoModel jogo)
        {
            try{
                if (ModelState.IsValid) 
                {
                    _jogoRepositorio.Create(jogo);
                    TempData["MessagemSucess"] = "Jogo cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(jogo);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível efetuar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(JogoModel jogo)
        {
            try{
                if (ModelState.IsValid)
                {
                    _jogoRepositorio.Update(jogo);
                    TempData["MessagemSucess"] = "Cadastro editado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(jogo);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível editar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

    }
}

VioletGames/Views/Jogo/Create.cshtml
@using VioletGames.Data.Enums
@model JogoModel
@{
    Layout = "_Layout";
}

<nav>
    <div class="text-center">
        <h1>Cadastrar Jogos</h1><br />
    </div>
    <form asp-controller="Jogo" asp-action="Create" method="post" class="singin">
        <div class="mb-3">
            <label for="Name" class="form-label">Nome</label>
            <input type="text" asp-for="Name" class="form-control" style="width: 560px; display: inline;" placeholder="Digite o nome">
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div class="mb-3">
            <select asp-for="CategoryConsole" class="form-control" style="width: 150px; display: inline;">
                <option value="">Console</option>
                <option value="@CategoryConsole.Ps1">PS1</option>
                <option value="@CategoryConsole.Ps2">PS2</option>
                <option value="@CategoryConsole.Ps3">PS3</option>
                <option value="@CategoryConsole.Ps4">PS4</option>
                <option value="@CategoryConsole.Ps5">PS5</option>
                <option value="@CategoryConsole.Wii">Wii</option>
                <option value="@CategoryConsole.Pc">PC</option>
                <option value="@CategoryConsole.Nitendo64">Nitendo64</option>
                <option value="@CategoryConsole.Xbox360">Xbox360</option>
                <option value="@CategoryConsole.XboxOne">XboxOne</option>
            </select>
            @Html.ValidationMessageFor(x => x.CategoryConsole)
            <select asp-for="StatusJogo" class="form-control" style="width: 150px; display: inline;">
                <option value="">Status</option>
                <option value="@StatusLocation.Livre">Livre</option>
                <option value="@StatusLocation.Pedente">Pendente</option>
                <option value="@StatusLocation.Desativado">Desativado</option>
                <option value="@StatusLocation.Desativado">Usando</option>
            </select>
            @Html.ValidationMessageFor(x => x.StatusJogo)
        </div>
        <div class="mb-3">
            <label for="Price" class="form-label">Valor (Dia)</label>
            <input type="text" asp-for="PriceHour" class="form-control" style="width: 360px; display: inline;" placeholder="00,00">
            @Html.ValidationMessageFor(x => x.PriceHour)
        </div><br />
        <div class="singin">
            <button type="submit" class="btn btn-primary">Cadastrar</button>
            <a role="button" class="btn btn-info" asp-controller="Jogo" asp-action="Index">Voltar</a>
        </div>
    </form>

</nav>

VioletGames/Views/Jogo/DeleteConfirm.cshtml
@model JogoModel
@{
    Layout = "_Layout";
}

<nav >
    <div class="text-center">
        <h3>Realmente deseja apagar o Jogo (@Model.Name)?</h3>
        <a role="button" class="btn btn-success" asp-controller="Jogo" asp-route-id="@Model.Id" asp-action="Delete">Deletar</a>
        <a role="button" class="btn btn-danger" asp-controller="Jogo" asp-action="Index">Cancelar</a>
    </div>
</nav>

VioletGames/Views/Jogo/Edit.cshtml
@using VioletGames.Data.Enums
@model JogoModel
@{
    Layout = "_Layout";
}

<nav >
    <div class="text-center">
        <h1>Editar Jogo</h1><br />
    </div>
    <form asp-controller="Jogo" asp-action="Create" method="post" class="singin">
        <div class="mb-3">
            <label for="Name" class="form-label">Nome</label>
            <input type="text" asp-for="Name" class="form-control" style="width: 560px; display: inline;" placeholder="Digite o nome">
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div class="mb-3">
            <select asp-for="CategoryConsole" class="form-control" style="width: 150px; display: inline;">
                <option value="">Console</option>
                <option value="@CategoryConsole.Ps1">PS1</option>
                <option value="@CategoryConsole.Ps2">PS2</option>
                <option value="@CategoryConsole.Ps3">PS3</option>
                <option value="@CategoryConsole.Ps4">PS4</option>
                <option value="@CategoryConsole.Ps5">PS5</option>
                <option value="@CategoryConsole.Wii">Wii</option>
                <option value="@CategoryConsole.Pc">PC</option>
                <option value="@CategoryConsole.Nitendo64">Nitendo64</option>
                <option value="@CategoryConsole.Xbox360">Xbox360</option>
                <option value="@CategoryConsole.XboxOne">XboxOne</option>
            </select>
            @Html.ValidationMessageFor(x => x.CategoryConsole)
            <select asp-for="StatusJogo" class="form-control" style="width: 150px; display: inline;">
                <option value="">Status</option>
                <option value="@StatusLocation.Livre">Livre</option>
                <option value="@StatusLocation.Pedente">Pendente</option>
                <option value="@StatusLocation.Desativado">Desativado</option>
                <option value="@StatusLocation.Usando">Usando</option>
            </select>
            @Html.ValidationMessageFor(x => x.StatusJogo)
        </div>
        <div class="mb-3">
            <label for="Price" class="form-label">Valor(Hora)</label>
            <input type="text" asp-for="PriceHour" class="form-control" style="width: 360px; display: inline;" placeholder="00,00">
            @Html.ValidationMessageFor(x => x.PriceHour)
        </div><br />
        <div class="singin">
            <button type="submit" class="btn btn-primary">Editar</button>
            <a role="button" class="btn btn-info" asp-controller="Jogo" asp-action="Index">Voltar</a>
        </div>
    </form>

</nav>

VioletGames/Views/Jogo/Index.cshtml
@model List<JogoModel>
@{
    Layout = "_Layout";
}

<nav >
    <div class="text-center">
        <br />
        <table class="table table-content" id="table-consoles">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Valor (H)</th>
                    <th scope="col">Status</th>
                    <th scope="col"><a role="button" class="btn btn-success" asp-controller="Jogo" asp-action="Create"><img src="~/lib/bottons/add.png" width="30" height="30"></a></th>
                </tr>
            </thead>
            <tbody>
                <!--Listar contatos SE existir-->
                @if (Model != null && Model.Any())
                {
                    <!--Erro nesse Any-->
                    foreach (JogoModel Jogo in Model)
                    {
                        <tr>
                            <th scope="row">@Jogo.Id</th>
                            <td>@Jogo.Name</td>
                            <td>@Jogo.CategoryConsole</td>
                            <td>@Jogo.PriceHour</td>
                            <td>@Jogo.StatusJogo</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                    <a role="button" class="btn btn-success" asp-route-id="@Jogo.Id" asp-controller="Agendamento" asp-action="CreateGame"><img src="~/lib/bottons/scheduler.png" width="25" height="25"></a>
                                    <a role="button" class="btn btn-warning" asp-route-id="@Jogo.Id" asp-controller="Jogo" asp-action="Edit"><img src="~/lib/bottons/edit.png" width="20" height="20"></a>
                                    <a role="button" class="btn btn-danger" asp-route-id="@Jogo.Id" asp-controller="Jogo" asp-action="DeleteConfirm"><img src="~/lib/bottons/Del.png" width="25" height="25"></a>
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</nav>