VioletGames/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using VioletGames.Models;
using VioletGames.Util.Validator;
using VioletGames.Data.Filters;
using VioletGames.Repositorio;

namespace VioletGames.Controllers
{
    [PageUserLogin]
    [PageUserAdmin]
    public class FuncionarioController : Controller
    {
        //Extrai variavel FuncionarioRepositorio
        private readonly IFuncionarioRepositorio _funcionarioRepositorio;

        public FuncionarioController(IFuncionarioRepositorio funcionarioRepositorio)
        {
            //injeta para dentro de FuncionarioController
            _funcionarioRepositorio = funcionarioRepositorio;
        }

        //Métodos Get
        public IActionResult Index()
        {
            //lista a busca feita no banco
            ViewData["Title"] = "Funcionários";
            List<FuncionarioModel> funcionarios = _funcionarioRepositorio.SearchAll();

            return View(funcionarios);
        }

        public IActionResult Create()
        {
            ViewData["Title"] = "Funcionários";
            return View();
        }

        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Funcionários";
            FuncionarioModel funcionario = _funcionarioRepositorio.ListForIDEmployee(id);
            return View(funcionario);
        }

        public IActionResult DeleteConfirm(int id)
        {
            ViewData["Title"] = "Funcionários";
            FuncionarioModel funcionario = _funcionarioRepositorio.ListForIDEmployee(id);

            return View(funcionario);
        }

        public IActionResult Delete(int id) 
        {
            try
            {
                bool deleted = _funcionarioRepositorio.Delete(id);

                if (deleted)
                {
                    TempData["MessagemSucess"] = "Funcionário deletado com sucesso!";
                }
                else{
                    TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente.";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível deletar o cadastro! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        //Métodos Post
        [HttpPost]
        public IActionResult Create(FuncionarioModel funcionario) 
        {
            try{
                if (ModelState.IsValid)
                {
                    if (!Validator.IsCPF(funcionario.CPF))
                    { 
                        TempData["MessagemError"] = "CPF informado Inválido!";
                        return View(funcionario);
                    }
                    if(!Validator.IsPhone(funcionario.Phone))
                    {
                        TempData["MessagemError"] = "Telefone informado Inválido!";
                        return View(funcionario);
                    }

                    if(!Validator.IsDateValid(funcionario.DateBirthday))
                    {
                        TempData["MessagemError"] = "Data informada Inválida!";
                        return View(funcionario);
                    }

                    _funcionarioRepositorio.Create(funcionario);
                    TempData["MessagemSucess"] = "Funcionário cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(funcionario);
            }
            catch (System.Exception erro){
                TempData["MessagemError"] = $"Não foi possível efetuar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(FuncionarioModel funcionario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!Validator.IsCPF(funcionario.CPF))
                    {
                        TempData["MessagemError"] = "CPF informado Inválido!";
                        return View(funcionario);
                    }
                    if (!Validator.IsPhone(funcionario.Phone))
                    {
                        TempData["MessagemError"] = "Telefone informado Inválido!";
                        return View(funcionario);
                    }

                    _funcionarioRepositorio.Update(funcionario);
                    TempData["MessagemSucess"] = "Cadastro editado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(funcionario);
            }
            catch (System.Exception erro)
            {
                TempData["MessagemError"] = $"Não foi possível editar o cadastrado! Tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

    }
}

VioletGames/Views/Funcionario/Create.cshtml
@using VioletGames.Data.Enums
@model FuncionarioModel
@{
    Layout = "_Layout";
}

<nav>
    <div class="text-center">
        <h1>Cadastrar Funcionário</h1><br />
    </div>
    <form asp-controller="Funcionario" asp-action="Create" method="post" class="singin">
        <div class="mb-3">
            <label for="Name" class="form-label">Nome</label>
            <input type="text" asp-for="Name" class="form-control" style="width: 560px; display: inline;" placeholder="Digite o nome">
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div class="mb-3">
            <label for="Date" class="form-label">Data de Nascimento</label>
            <input type="date" asp-for="DateBirthday" class="form-control" style="width: 160px; display: inline;" placeholder="00/00/00">
            @Html.ValidationMessageFor(x => x.DateBirthday)
        </div>
        <div class="mb-3">
            <label for="Email" class="form-label">Email</label>
            <input type="text" asp-for="Email" class="form-control" style="width: 360px; display: inline;" placeholder="nome@exemplo.com">
            @Html.ValidationMessageFor(x => x.Email)
        </div>
        <div class="mb-3">
            <label for="CPF" class="form-label">CPF</label>
            <input type="text" asp-for="CPF" class="form-control" style="width: 150px; display: inline;" placeholder="000000000-00">
            @Html.ValidationMessageFor(x => x.CPF)
            <label for="RG" class="form-label">RG</label>
            <input type="text" asp-for="RG" class="form-control" style="width: 150px; display: inline; " placeholder="000000000-00">
        </div>
        <div class="mb-3">
            <label for="Date" class="form-label">Admissão</label>
            <input type="date" asp-for="DateAdmission" class="form-control" style="width: 150px; display: inline;" placeholder="00/00/00">
            <label for="Pay" class="form-label">Salário</label>
            <input type="text" asp-for="Pay" class="form-control" style="width: 100px; display: inline;" placeholder="0,00">
            <label for="Office" class="form-label">Cargo</label>
            <select asp-for="Office" class="form-control" style="width: 150px; display: inline;">
                <option value="">Selecione</option>
                <option value="@Office.Boss">Gerente</option>
                <option value="@Office.Employee">Atendente</option>
            </select>
            @Html.ValidationMessageFor(x => x.Office)
        </div>
        <div class="mb-3">
            <label for="Phone" class="form-label">Telefone</label>
            <input type="text" asp-for="Phone" class="form-control" style="width: 260px; display: inline;" placeholder="(11) 00000-0000">
            @Html.ValidationMessageFor(x => x.Phone)
        </div>
        <div class="mb-3">
            <label for="Address" class="form-label">CEP</label>
            <input type="text" asp-for="City" class="form-control" style="width: 200px; display: inline;" placeholder="000000000-000">
            <input type="text" asp-for="State" class="form-control" style="width: 120px; display: inline;" placeholder="Estado">
        </div>
        <div class="mb-3">
            <label for="Address" class="form-label">Cidade</label>
            <input type="text" asp-for="City" class="form-control" style="width: 400px; display: inline;" placeholder="Mauá">
        </div>
        <div class="mb-3">
            <label for="Address" class="form-label">Rua</label>
            <input type="text" asp-for="Address" class="form-control" style="width: 360px; display: inline;" placeholder="Rua exemplo">
            <label for="Address" class="form-label">Número</label>
            <input type="text" asp-for="Number" class="form-control" style="width: 130px; display: inline;" placeholder="0000">
        </div>
        <div class="singin">
            <button type="submit" class="btn btn-primary">Cadastrar</button>
            <a role="button" class="btn btn-info" asp-controller="Funcionario" asp-action="Index">Voltar</a>
        </div>
    </form>
</nav>

VioletGames/Views/Funcionario/DeleteConfirm.cshtml
@model FuncionarioModel
@{
    Layout = "_Layout";
}

<nav>
    <div class="text-center">
    <h3>Realmente deseja apagar o Funcionário (@Model.Name)?</h3>
    <a role="button" class="btn btn-success" asp-controller="Funcionario" asp-route-id="@Model.Id" asp-action="Delete">Deletar</a>
    <a role="button" class="btn btn-danger" asp-controller="Funcionario" asp-action="Index">Cancelar</a>
</div>
</nav>

VioletGames/Views/Funcionario/Edit.cshtml
@using VioletGames.Data.Enums
@model FuncionarioModel
@{
    Layout = "_Layout";
}

<nav>
    <div class="text-center">
        <h1>Editar Funcionário</h1><br />
    </div>
    <form asp-controller="Funcionario" asp-action="Edit" method="post" class="singin">
        <div class="mb-3">
            <label for="Name" class="form-label">Nome</label>
            <input type="text" asp-for="Name" class="form-control" style="width: 560px; display: inline;" placeholder="Digite o nome">
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div class="mb-3">
            <label for="Date" class="form-label">Data de Nascimento</label>
            <input type="date" asp-for="DateBirthday" class="form-control" style="width: 160px; display: inline;" placeholder="00/00/00">
            @Html.ValidationMessageFor(x => x.DateBirthday)
        </div>
        <div class="mb-3">
            <label for="Email" class="form-label">Email</label>
            <input type="text" asp-for="Email" class="form-control" style="width: 360px; display: inline;" placeholder="nome@exemplo.com">
            @Html.ValidationMessageFor(x => x.Email)
        </div>
        <div class="mb-3">
            <label for="CPF" class="form-label">CPF</label>
            <input type="text" asp-for="CPF" class="form-control" style="width: 150px; display: inline;" placeholder="000000000-00">
            @Html.ValidationMessageFor(x => x.CPF)
            <label for="RG" class="form-label">RG</label>
            <input type="text" asp-for="RG" class="form-control" style="width: 150px; display: inline; " placeholder="000000000-00">
        </div>
        <div class="mb-3">
            <label for="Date" class="form-label">Admissão</label>
            <input type="date" asp-for="DateAdmission" class="form-control" style="width: 150px; display: inline;" placeholder="00/00/00">
            <label for="Pay" class="form-label">Salário</label>
            <input type="text" asp-for="Pay" class="form-control" style="width: 100px; display: inline;" placeholder="0,00">
            <label for="Office" class="form-label">Cargo</label>
            <select asp-for="Office" class="form-control" style="width: 150px; display: inline;">
                <option value="">Selecione</option>
                <option value="@Office.Boss">Gerente</option>
                <option value="@Office.Employee">Atendente</option>
            </select>
            @Html.ValidationMessageFor(x => x.Office)
        </div>
        <div class="mb-3">
            <label for="Phone" class="form-label">Telefone</label>
            <input type="text" asp-for="Phone" class="form-control" style="width: 260px; display: inline;" placeholder="(11) 00000-0000">
            @Html.ValidationMessageFor(x => x.Phone)
        </div>
        <div class="mb-3">
            <label for="Address" class="form-label">CEP</label>
            <input type="text" asp-for="City" class="form-control" style="width: 200px; display: inline;" placeholder="000000000-000">
            <input type="text" asp-for="State" class="form-control" style="width: 120px; display: inline;" placeholder="Estado">
        </div>
        <div class="mb-3">
            <label for="Address" class="form-label">Cidade</label>
            <input type="text" asp-for="City" class="form-control" style="width: 400px; display: inline;" placeholder="Mauá">
        </div>
        <div class="mb-3">
            <label for="Address" class="form-label">Rua</label>
            <input type="text" asp-for="Address" class="form-control" style="width: 360px; display: inline;" placeholder="Rua exemplo">
            <label for="Address" class="form-label">Número</label>
            <input type="text" asp-for="Number" class="form-control" style="width: 130px; display: inline;" placeholder="0000">
        </div>
        <div class="singin">
            <button type="submit" class="btn btn-primary">Cadastrar</button>
            <a role="button" class="btn btn-info" asp-controller="Funcionario" asp-action="Index">Voltar</a>
        </div>
    </form>
</nav>

VioletGames/Views/Funcionario/Index.cshtml
@model List<FuncionarioModel>
@{
    Layout = "_Layout";
}

<nav>
    <div class="text-center">
        <br />
        <table class="table table-content" id="table-funcionarios">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Data Nasc.</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">CPF</th>
                    <th scope="col">Admissão</th>
                    <th scope="col">Cargo</th>
                    <th scope="col">Salário</th>
                    <th scope="col">
                        <a role="button" class="btn btn-success" asp-controller="Funcionario" asp-action="Create"><img src="~/lib/bottons/add.png" width="30" height="30"></a>
                    </th>
                </tr>
            </thead>
            <tbody>
                <!--Listar contatos SE existir-->
                @if (Model != null && Model.Any())
                {
                    foreach (FuncionarioModel funcionario in Model)
                    {
                        <tr>
                            <th scope="row">@funcionario.Id</th>
                            <td>@funcionario.Name</td>
                            <td>@funcionario.DateBirthday.ToString("dd/MM/yyyy")</td>
                            <td>@funcionario.Email</td>
                            <td>@funcionario.Phone</td>
                            <td>@funcionario.CPF</td>
                            <td>@funcionario.DateAdmission</td>
                            <td>@(funcionario.Office == VioletGames.Data.Enums.Office.Boss ? "Gerente" : "Atendente")</td>
                            <td>@funcionario.Pay</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                    <a role="button" class="btn btn-warning" asp-route-id="@funcionario.Id" asp-controller="Funcionario" asp-action="Edit"><img src="~/lib/bottons/edit.png" width="20" height="20"></a>
                                    <a role="button" class="btn btn-danger" asp-route-id="@funcionario.Id" asp-controller="Funcionario" asp-action="DeleteConfirm"><img src="~/lib/bottons/Del.png" width="25" height="25"></a>
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

</nav>